enum MeshCommandType {
  appStart(1),
  sendTextMessage(2),
  sendChannelTextMessage(3),
  getContacts(4),
  getDeviceTime(5),
  setDeviceTime(6),
  sendSelfAdvert(7),
  setAdvertName(8),
  addUpdateContact(9),
  syncNextMessage(10),
  setRadioParams(11),
  setRadioTxPower(12),
  resetPath(13),
  setAdvertLatLon(14),
  removeContact(15),
  shareContact(16),
  exportContact(17),
  importContact(18),
  reboot(19),
  getBatteryAndStorage(20),
  setTuningParams(21),
  deviceQuery(22),
  exportPrivateKey(23),
  importPrivateKey(24),
  sendRawData(25),
  sendLogin(26),
  sendStatusReq(27),
  hasConnection(28),
  logout(29),
  getContactByKey(30),
  getChannel(31),
  setChannel(32),
  signStart(33),
  signData(34),
  signFinish(35),
  sendTracePath(36),
  setDevicePin(37),
  setOtherParams(38),
  sendTelemetryReq(39),
  getCustomVars(40),
  setCustomVar(41),
  getAdvertPath(42),
  getTuningParams(43),
  binaryReq(50),
  factoryReset(51),
  pathDiscovery(52),
  setFloodScope(54),
  getStats(56),
  sendControlData(55),
  sendAnonReq(57),
  setAutoaddConfig(58),
  getAutoaddConfig(59),
  getAllowedRepeatFreq(60),
  setPathHashMode(61),
  setDefaultFloodScope(63),
  getDefaultFloodScope(64);

  const MeshCommandType(this.code);
  final int code;
}

enum MeshPacketType {
  ok(0),
  error(1),
  contactStart(2),
  contact(3),
  contactEnd(4),
  selfInfo(5),
  msgSent(6),
  contactMsgRecv(7),
  channelMsgRecv(8),
  currentTime(9),
  noMoreMsgs(10),
  contactUri(11),
  battery(12),
  deviceInfo(13),
  privateKey(14),
  disabled(15),
  contactMsgRecvV3(16),
  channelMsgRecvV3(17),
  channelInfo(18),
  signStart(19),
  signature(20),
  customVars(21),
  advertPath(22),
  tuningParams(23),
  stats(24),
  autoaddConfig(25),
  allowedRepeatFreq(26),
  defaultFloodScope(28),
  advertisement(0x80),
  pathUpdate(0x81),
  ack(0x82),
  messagesWaiting(0x83),
  rawData(0x84),
  loginSuccess(0x85),
  loginFailed(0x86),
  statusResponse(0x87),
  logData(0x88),
  traceData(0x89),
  pushCodeNewAdvert(0x8a),
  telemetryResponse(0x8b),
  binaryResponse(0x8c),
  pathDiscoveryResponse(0x8d),
  controlData(0x8e),
  contactDeleted(0x8f),
  contactsFull(0x90);

  const MeshPacketType(this.code);
  final int code;

  static MeshPacketType? fromCode(int code) {
    for (final type in values) {
      if (type.code == code) return type;
    }
    return null;
  }
}

const payloadTypeNames = <String>[
  'REQ',
  'RESPONSE',
  'TEXT_MSG',
  'ACK',
  'ADVERT',
  'GRP_TXT',
  'GRP_DATA',
  'ANON_REQ',
  'PATH',
  'TRACE',
  'MULTIPART',
  'CONTROL',
];

const routeTypeNames = <String>[
  'TC_FLOOD',
  'FLOOD',
  'DIRECT',
  'TC_DIRECT',
];
